services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      PORT: 5001
      HOST: 0.0.0.0
      DEBUG: "True"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudshop
      DB_USER: admin
      DB_PASSWORD: admin123

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "5002:5002"
    restart: unless-stopped
    environment:
      PORT: 5002
      HOST: 0.0.0.0
      DEBUG: "True"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudshop
      DB_USER: admin
      DB_PASSWORD: admin123

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "5003:5003"
    restart: unless-stopped
    environment:
      PORT: 5003
      HOST: 0.0.0.0
      DEBUG: "True"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudshop
      DB_USER: admin
      DB_PASSWORD: admin123
      USER_SERVICE_URL: http://user-service:5001
      PRODUCT_SERVICE_URL: http://product-service:5002

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "5004:5004"
    restart: unless-stopped
    environment:
      PORT: 5004
      HOST: 0.0.0.0
      DEBUG: "True"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudshop
      DB_USER: admin
      DB_PASSWORD: admin123


  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cloudshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

volumes:
  postgres_data:

