apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: cloudshop

spec:
  type: ClusterIP

  selector:
    app: notification-service 

  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
      
