apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.product.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: "{{ .Values.product.image.repository }}:{{ .Values.product.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: product-service-config
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          ports:
          - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
