FROM python:3.14-slim

WORKDIR /app

# Copy only requirements first (better Docker cache)
COPY user-service/requirements.txt user-service/
COPY product-service/requirements.txt product-service/
COPY order-service/requirements.txt order-service/
COPY notification-service/requirements.txt notification-service/

# Install dependencies
RUN pip install --no-cache-dir \
    -r user-service/requirements.txt \
    -r product-service/requirements.txt \
    -r order-service/requirements.txt \
    -r notification-service/requirements.txt

# Copy the complete source code
COPY . .

CMD ["bash"]