FROM python:3.14-slim

WORKDIR /app

# Copy only the services (better Docker cache)
COPY user-service/ user-service/
COPY product-service/ product-service/
COPY order-service/ order-service/
COPY notification-service/ notification-service/

# Install dependencies
RUN pip install --no-cache-dir \
    -r user-service/requirements.txt \
    -r product-service/requirements.txt \
    -r order-service/requirements.txt \
    -r notification-service/requirements.txt

CMD ["bash"]